chore: ensure services up before connecting

diff --git a/.devcontainer/socat_cache b/.devcontainer/socat_cache
--- a/.devcontainer/socat_cache
+++ b/.devcontainer/socat_cache
@@ -8,6 +8,11 @@ LOGFILE=/tmp/socat_cache.log
 case "$1" in
     start)
         echo "Starting Socat Cache Port Forwarding..."
+        while ! nc -zw 10 cache 6379
+        do
+            echo "Can't connect to cache:6379"
+            sleep 2
+        done
         while :
         do
             /usr/bin/nohup /usr/bin/socat -d -lf $LOGFILE TCP4-LISTEN:6379,bind=127.0.0.1,reuseaddr,fork TCP4:cache:6379 >/dev/null 2>&1 &
diff --git a/.devcontainer/socat_mysql b/.devcontainer/socat_mysql
--- a/.devcontainer/socat_mysql
+++ b/.devcontainer/socat_mysql
@@ -8,6 +8,11 @@ LOGFILE=/tmp/socat_mysql.log
 case "$1" in
     start)
         echo "Starting Socat MySQL Port Forwarding..."
+        while ! nc -zw 10 mysql 3306
+        do
+            echo "Can't connect to mysql:3306"
+            sleep 2
+        done
         while :
         do
             /usr/bin/nohup /usr/bin/socat -d -lf $LOGFILE TCP4-LISTEN:3309,bind=127.0.0.1,reuseaddr,fork TCP4:mysql:3306 >/dev/null 2>&1 &
